# main text of home
title: "Riglen Group"
description: |
  Landing Page for Riglen Group
  
markdown: kramdown
kramdown:
  hard_wrap: true

# future: true
unpublished: false

lang: en

google_analytics: 'G-7QX38F5QZS'

contact:
  headquarter: "Zurich, Switzerland"
  email: "hello@riglen.com"
  phone: "+41 (0) 79 749 72 47"

collections_dir: collections
collections:
  services:
    permalink: /:collection/:slug
    output: true
  solutions:
    permalink: /:collection/:slug
    output: true
  blogs:
    permalink: /insights/:collection/:path
    output: true
  news:
    permalink: /insights/:collection/:path
    output: true
  stories:
    permalink: /insights/:collection/:slug
    output: false
  locations:
    permalink: /about/:collection/:slug
    output: false
  staff:
    permalink: /about/:collection/:slug
    output: false
  industries:
    permalink: /about/:collection/:slug
    output: false
  partners:
    permalink: /about/:collection/:slug
    output: false
      
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  
exclude:
  - "Rakefile"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "FAQ.md"

emptyArray: []

defaults:
  - scope:
      path: "assets/**"
    values:
      sitemap: false